### ISSUE TITLE
Use unsupervised classification to detect sand pixels

### ISSUE THREAD

**Issue by chrisleaman** [npucino/sandpyper#10]
From working through the example notebooks, it seems the most labor intensive step is to detect which points are sand. Currently, sandpyper uses an unsupervised clustering algorithm to group pixels, but a human operator still needs to review the grouping and assign the clusters to sand. From my understanding, this would need to be done for each new dem/ortho file.

A potential improvement would be directly detect which pixels in the dem correspond to sand pixels. https://github.com/kvos/CoastSat has an approach based on satellite imagery which works well. I don't think this can be directly transferred to sandpyper though as the CoastSat relies on multispectral bands (R, G, B, NIR, SWIR1) while sandpyper would be only used on aerial imagery. Nevertheless, if a classifier can be trained to detect sand solely on the aerial imagery, it might result in a less labour intesive processsing pipeline. 

![RjxpLYiqWf](https://user-images.githubusercontent.com/7591552/132978957-cf4b7d4e-0008-4e39-aae3-86697650d560.png)

@npucino, I'm sure you've thought of how best to classify sand points - did you have any thoughts about the CoastSat approach? Note this is a suggestion just for future improvement and outside the scope of the JOSS review.

**Comment by npucino** [comment]
Hi @chrisleaman , thx for the reviews and suggestions!

Absolutely agree with you.

But, unfortunately, working with consumer-grade uncalibrated RGB sensors on UAVs is a bit more challenging than calibrated atmospheric-corrected multispectral imagers. And at 2.5cm resolution the illumination conditions really changes the way the sensor captures the colors. Plus, **at the moment**, Sandpyper allows to work on profiles only (series of points along cross-shore transects, really), whose lack in spatial context information (though it could be done using sequence-specific neural networks like lstm or transformers).

The scope of the unsupervised (lengthy) procedure is twofold:
- work around the challenges that supervised classification in this case has
- create ad-hoc training dataset for supervised classifiers that users can create outside Sandpyper

**Good news**

1. With Sandpyper I have created a training dataset of **a few millions points**, which I could add into the package for anyone to play around with and test supervised classification techniques.
2. **CoastSat uses Multi Layer Perceptron** neural network which doesn't take spatial context into consideration neither (but has the most powerful water discriminator SWIR and NIR bands), so maybe a simple neural network without spatial context can also have a chance (though only RGB is definitely harder)

 **Super good news**

As part of another chapter of my PhD, I am actually implementing a raster-based approach and the sand no-sand classification is tackled with context-aware convolutional neural networks, with much better generalisation power (across time and locations).
Therefore, once I will have time to properly clean this code, it will be implemented in Sandpyper as a completely new big feature (raster-based).
This will enable users to classify sand vs no-sand with my pre-trained model or fine-tune it to their locations.
But, it is a **future feature** for now!

**Comment by chrisleaman** [comment]
Thanks @npucino, I had forgotten about the fact sandpyper currently is just in profile mode at the moment - this is something that is definitely more suited to the raster based analysis you have planned. I agree the lack of additional bands combined with different lighting conditions makes this problem at lot harder than compared with satellite imagery. Looking forward to the new raster based features you're planning on implementing though!

**Comment by npucino** [comment]
Closed this issue as it is a (pertinent and useful) suggestion.
