### ISSUE TITLE
[JOSS REVIEW] Example notebook minor suggestions

### ISSUE THREAD

**Issue by chrisleaman** [npucino/sandpyper#9]
Hi @npucino,

Great work in creating these example notebooks, it was pretty easy for me to work through all three notebooks and understand how everything in the package works.

My comments below are mainly minor suggestions about providing some additional explaination for anyone using these notebooks. Comments are for https://github.com/openjournals/joss-reviews/issues/3666#issuecomment-913647064. I've created two other issues for some trickier problems (https://github.com/npucino/sandpyper/issues/7, https://github.com/npucino/sandpyper/issues/8).

## 1 - Introduction and data preparation.ipynb

1. Can you define the term "LoD" before you use it here? I had to scroll down a bit before I got the definition.
https://github.com/npucino/sandpyper/blob/ce542c6f8a8f7a046e7d0017b29dfacc0420cbe0/examples/1%20-%20Introduction%20and%20data%20preparation.ipynb#L103

2. When talking about the demo data, I think it should be more clear that these are the inputs that sandpyper needs (and not the output that sandpyper generates). It would also be helpful to briefly describe how each input is typically created, i.e. orthos and dems are stitched together using photogrammetry software (Pix4D), while transect and mask files are manually created in a GIS software (QGis, ARCGIS). You've provided examples later in the notebook, it'd be good just add a summary sentence or two here as well.
https://github.com/npucino/sandpyper/blob/ce542c6f8a8f7a046e7d0017b29dfacc0420cbe0/examples/1%20-%20Introduction%20and%20data%20preparation.ipynb#L134

3. We need to change the path of a lot of path varibles, depending where we've saved the test_data. I suggest defining the parent path first and constructing the other paths based on this. Something like:

```
from pathlib import Path

test_data_folder = 'C:\Users\Chris\Desktop\sandpyper\examples\test_data'
ortho_path=Path(test_data_folder,"\orthos_1m\leo_20180920_ortho_resampled_1m.tif")
watermasks_path=Path(test_data_folder,"\clean\watermasks.gpkg")
shoremasks_path=Path(test_data_folder,"\clean\shoremasks.gpkg")
label_corr_path=Path(test_data_folder,"\clean\label_corrections.gpkg")
transect_path=Path(test_data_folder,"\transects\leo_transects.gpkg")
transect_lod_path=Path(test_data_folder,"\lod_transects\leo_lod_transects.gpkg")
```

https://github.com/npucino/sandpyper/blob/ce542c6f8a8f7a046e7d0017b29dfacc0420cbe0/examples/1%20-%20Introduction%20and%20data%20preparation.ipynb#L1164-L1169

4. Can you double check the leo features in the label corrections file (`examples/test_data/clean/label_corrections.gpkg`) are in the correct location? Looks like some CRS mistake when I try load it in QGIS. The mar features in the correct location though.
https://github.com/npucino/sandpyper/blob/ce542c6f8a8f7a046e7d0017b29dfacc0420cbe0/examples/1%20-%20Introduction%20and%20data%20preparation.ipynb#L1418

5. I think an additional sentence explaining why points are being classified here would be good. Also update the reference to example notebook 2.
https://github.com/npucino/sandpyper/blob/ce542c6f8a8f7a046e7d0017b29dfacc0420cbe0/examples/1%20-%20Introduction%20and%20data%20preparation.ipynb#L1431

## 2 - Profiles extraction, unsupervised sand labelling and cleaning.ipynb

1. Again, easier to use the `pathlib.Path` approach here to define the parent folder rather than changing each variable.
https://github.com/npucino/sandpyper/blob/ce542c6f8a8f7a046e7d0017b29dfacc0420cbe0/examples/2%20-%20Profiles%20extraction%2C%20unsupervised%20sand%20labelling%20and%20cleaning.ipynb#L118-L120

2. Add the command to export the dataframe to csv: `P.profiles.to_csv('profiles.csv')`
https://github.com/npucino/sandpyper/blob/ce542c6f8a8f7a046e7d0017b29dfacc0420cbe0/examples/2%20-%20Profiles%20extraction%2C%20unsupervised%20sand%20labelling%20and%20cleaning.ipynb#L2799

## 3 - Profile dynamics.ipynb
(I couldn't link to line numbers in this file - perhaps the notebook is too big for github?)

1. **Section: "Plot: LoD normality check"**: The normality check plots show that the distributions fail the normality checks. Can you talk about what (if any) implications this has? 

2. **Section: "Plot: multi-scale MECS and volumetrics"**: The plots for `D.plot_transect_mecs(location='mar',tr_id=10)` and `D.plot_transect_mecs(location='mar', lod=D.lod_df, tr_id=10)` seem fairly similar (though I see some variation in the shaded area). Could you add a couple of sentences discussing the difference between using LoD and not?

**Comment by npucino** [comment]
Thanks @chrisleaman for this review! Very useful and constructive suggestions that I will implement very soon.

For now I want to just reply this:

`Can you double check the leo features in the label corrections file (examples/test_data/clean/label_corrections.gpkg) are in the correct location? Looks like some CRS mistake when I try load it in QGIS. The mar features in the correct location though.`

Unfortunately, storing all locations (multiple locations and multiple CRSs) into one single Geopandas.Geodataframe allow only 1 CRS to use. Thus, I digitised all correction polygons with EPSG 32754, which is the correct one for Marengo but the wrong one for St. Leonards (EPSG 32755). Unfortunately,  we would need either:
1. one geodataframe per location with the actual location CRS
2. a geodataframe which stores multiple CRSs, say, some rows with EPSG 32754 and others EPSG 32755, which is not possible to my knowledge.

I must make clear this somewhere, very important, thanks for reporting this!

**Comment by npucino** [comment]
Here there are the suggestions implemented.
>**Sorry for the rudimental images snapshots,** I don't know how to reference notebook lines as links and couldn't find a solution in 5 minutes of googling.

### 1.1 Earlier definition of LoD
I added its definition straight directly in the introduction.

![image](https://user-images.githubusercontent.com/44853536/134099413-c42c14cf-6291-4beb-a122-4516a5d07dc8.png)

### 1.2 Better definition of input data
I added a better explaination of each input, making clear that these are inputs and not what Sandpyper produces.

![image](https://user-images.githubusercontent.com/44853536/134099443-f2140252-b143-4f9e-a478-7b4fd75bd04d.png)

### 1.3 & 2.1 Implementation of pathlib Path to manage paths
I used the strategy you suggested and it is way better.

![image](https://user-images.githubusercontent.com/44853536/134099524-7b8bb8e9-3224-4592-834e-0e8eef5ccbbb.png)

### 1.4 CRS misplacement
Explained here: https://github.com/npucino/sandpyper/issues/9#issuecomment-917816519

### 1.5 additional explanation of point classification importance and updated link to notebook 2
I wrote an extra paragraph where I introduce the challenges and the why I coded this way (for now).
And updated the link to NB-2.

![image](https://user-images.githubusercontent.com/44853536/134099671-2d43a325-d089-4829-9f52-dd2ab68cb6b0.png)

### 2.2 save to .csv command 
Added.
![image](https://user-images.githubusercontent.com/44853536/134099260-c0a3e79f-9db2-424b-a6de-6b31d8b964d5.png)


### 3.1 Normality check importance and consequences explanation
I better explained why it is important to test the normality of the error distributions and the consequences on the decision of most suitable error metric, with reference to one of the most important literature that best explain this concept for this type of data.

![image](https://user-images.githubusercontent.com/44853536/134099874-a24c9e29-968e-452d-868e-aa24aef482a9.png)

### 3.2 Plot transect mecs with and without LoD better explanation
I added a few words on the importance of using LoD despite the difference being small.

![image](https://user-images.githubusercontent.com/44853536/134099781-d9d159db-ac26-4fd3-87f2-19591e283ba3.png)
![image](https://user-images.githubusercontent.com/44853536/134099805-a48b0d20-2f8e-47fe-aee2-ea3c6df2c937.png)

Cheers

**Comment by chrisleaman** [comment]
Hi @npucino, great work with these changes! I really like the additional guidance and discussion you've provided, especially in notebook 3. It'll be especially helpful for those that aren't familiar with these LoD concepts (like me!). 

This issue was addressed with the following commits:

- 785ffca04c52c877002e390571d669954a6442cf
- 174df4bfebb0a5bdf9713fc482072c29799faf04
- 7b2cf21418283b5d1108a5dd07016fdbee44d834
- 324f2c96de90fd6611a7775ee87d82a6fa9905f7
- 5c8a4549c435c7d1ad2a5daf1aba1b480599a4cf
- 785ffca04c52c877002e390571d669954a6442cf
- 12e5965ea163f8858765574c01759e8f1594da42 
- ab8411ee195e6756c9bcf83c088878c9783f8d88
